export const DEMO_MOVIE = {
  type: 'movie',
  title: 'Lumen: Der Aufbruch',
  tagline: 'Eine cineastische Demo für das neue Modal',
  overview: 'Die Crew der Lumen wagt den Sprung in unerforschte Welten und enthüllt dabei eine Energiequelle, die alles verändern könnte. Zwischen Loyalität, Intrigen und berauschenden Bildern entfaltet sich ein Abenteuer, das für das Cinematic-Layout entworfen wurde.',
  summary: 'Die Crew der Lumen entdeckt eine Energiequelle, die das Schicksal der Menschheit verändern könnte.',
  runtimeMin: 142,
  contentRating: 'FSK 12',
  studio: 'Aurora Pictures',
  rating: 8.4,
  audienceRating: 8.0,
  userRating: 8.7,
  originallyAvailableAt: '2024-05-17',
  countries: [{ tag: 'Deutschland' }, { tag: 'Kanada' }],
  genres: [{ tag: 'Science-Fiction' }, { tag: 'Drama' }, { tag: 'Abenteuer' }],
  cast: [
    { name: 'Mara Lenz', role: 'Captain Alys Vega' },
    { name: 'Tariq Benassi', role: 'Navigator Elian Soh' },
    { name: 'Hannah Ko', role: 'Wissenschaftlerin Dr. Mira Han' },
  ],
  directors: [{ tag: 'Jonas Falk' }],
  writers: [{ tag: 'Lea Winter' }],
  producers: [{ tag: 'Studio Atlas' }],
  labels: [{ tag: 'Dolby Atmos' }, { tag: '4K' }],
  collections: [{ tag: 'Aurora-Saga' }],
  trailer: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  poster: '',
  ids: { imdb: 'tt0000001' },
  addedAt: '2024-06-01T12:00:00Z',
};

export const DEMO_SERIES = {
  type: 'tv',
  title: 'Aurora Station',
  tagline: 'Neue Horizonte in Serie',
  overview: 'Die Besatzung der Aurora Station schützt eine Außenposten an der Grenze des bekannten Raums. Jede Episode verbindet kosmische Rätsel mit persönlichen Geschichten – perfekt geeignet, um das Cinematic-Modal auszuprobieren.',
  summary: 'Ein orbitaler Außenposten ringt um Hoffnung und Zusammenhalt, während eine fremde Macht erwacht.',
  contentRating: 'TV-14',
  studio: 'Nebula Network',
  originallyAvailableAt: '2023-09-14',
  seasonCount: 2,
  genres: [{ tag: 'Science-Fiction' }, { tag: 'Drama' }],
  countries: [{ tag: 'USA' }, { tag: 'Island' }],
  creators: [{ tag: 'Elina Sørensen' }],
  cast: [
    { name: 'Noah Adler', role: 'Commander Ivar Hale' },
    { name: 'Sofia Idris', role: 'Ingenieurin Kaia Rhee' },
    { name: 'Helena Ruiz', role: 'Strategin Tala Voss' },
  ],
  seasons: [
    {
      title: 'Staffel 1',
      seasonNumber: 1,
      year: 2023,
      thumbFile: '',
      episodes: [
        {
          title: 'Kapitel Eins: Erwachen',
          seasonNumber: 1,
          episodeNumber: 1,
          durationMin: 54,
          originallyAvailableAt: '2023-09-14',
          audienceRating: 8.6,
        },
        {
          title: 'Kapitel Zwei: Grenzwelten',
          seasonNumber: 1,
          episodeNumber: 2,
          durationMin: 52,
          originallyAvailableAt: '2023-09-21',
          audienceRating: 8.2,
        },
      ],
    },
    {
      title: 'Staffel 2',
      seasonNumber: 2,
      year: 2024,
      thumbFile: '',
      episodes: [
        {
          title: 'Kapitel Dreizehn: Resonanz',
          seasonNumber: 2,
          episodeNumber: 1,
          durationMin: 56,
          originallyAvailableAt: '2024-02-08',
          audienceRating: 8.9,
        },
        {
          title: 'Kapitel Vierzehn: Echo',
          seasonNumber: 2,
          episodeNumber: 2,
          durationMin: 55,
          originallyAvailableAt: '2024-02-15',
          audienceRating: 8.7,
        },
      ],
    },
  ],
  poster: '',
  ids: { imdb: 'tt0000002' },
};
